# Generated by Django 2.0.2 on 2018-02-24 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now=True)),
                ('sabject', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(blank=True)),
                ('read_mark', models.BooleanField(default=False)),
                ('addressee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
